#!/bin/zsh
ME="${0:t:r}"
USAGE="usage: ${ME} .old .new [file...]"

if [[ $# -lt 2 ]]; then
	echo "${USAGE}" >&2
	exit 1
fi
OLD="$1"
case "${OLD}" in
.* )	;;
* )	echo "${USAGE}" >&2; exit 1;;
esac
NEW="$2"
case "${NEW}" in
.* )	;;
* )	echo "${USAGE}" >&2; exit 1;;
esac
# printf "OLD='${OLD}' NEW='${NEW}'\n"
shift 2
for f in ${@:-*}; do
	# echo "${f}"
	case "${f}" in
	*${OLD} )
		dn="${f:h}"
		bn="${f:t:r}"
		${DEBUG} /bin/mv "'${f:a}'" "'${dn}/${bn}${NEW}'"
		;;
	esac
done
